version: '2'

services:

  wordpress:
    extends:
      file: ../development/common.yml
      service: wordpress
    container_name: %PROJECT%_wp
    environment:
      WORDPRESS_DB_NAME: %PROJECT%
    volumes:
        - ./theme:/var/www/html/wp-content/themes/%PROJECT%
        - ./uploads:/var/www/html/wp-content/uploads        

  mysql:
    extends:
      file: ../development/common.yml
      service: mysql
    container_name: %PROJECT%_db
